<?xml version="1.0" encoding="utf-8"?><Database Name="Defaults" Class="ClientInfoTrackDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sofanpc;Initial Catalog=Defaults;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultsConnectionString" Provider="System.Data.SqlClient" />
</Database>